# Change these first
owner: rompslomp # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Rompslomp
    url: https://app.rompslomp.nl/up
  - name: Rompslomp API
    url: https://api.rompslomp.nl/api/v1/status
  # - name: IPv6 test
  #   url: forwardemail.net
  #   port: 80
  #   check: "tcp-ping"
  #   ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.rompslomp.nl
  theme: dark
  # baseUrl: /uptime
  logoUrl: https://d2lrgha3750i0i.cloudfront.net/assets/rompslomp-logo-2023-diap.svg
  name: Rompslomp status
  introTitle:
  introMessage:
  navbar:
    - title: Status
      href: /
    - title: Rompslomp
      href: https://app.rompslomp.nl

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

workflowSchedule:
  uptime: "*/30 * * * *"
